### ISSUE TITLE
Expand arrow is backwards

### ISSUE THREAD

**Issue by Scridgeon** [fablevi/HideItems#1]
The arrow to expand the hidden items is facing the wrong direction. This provided a poor indication of what will happen when the icon is clicked because it is currently fixed to always point to the right.

![image](https://github.com/fablevi/HideItems/assets/18316138/ab7e7097-b08a-49a2-b5e3-3b2f68042507)

Expectation:
The arrow should point to the left when the items are hidden.
The arrow should point to the right when the items are expanded.

**Comment by fablevi** [comment]
Hey, so its now updated :) thanks for reporting the issue
