### ISSUE TITLE
Change Settings behavior on click

### ISSUE THREAD

**Issue by Scridgeon** [fablevi/HideItems#2]
The settings menu should not be shown automatically on left-click. This action forces an additional screen click to hide the setting.

![image](https://github.com/fablevi/HideItems/assets/18316138/e0f700a9-721a-4d23-ad93-15dec9a62abb)

Expectations:
Left-clicking on the arrow will expand/collapse the arrow.

Suggested Options:
Remove the Settings as an option when clicking on the arrow
or
Move the settings to a right click action when clicking on the arrow

**Comment by Impasse52** [comment]
From what I can see, what you're asking for is the normal behavior. However, the moment I lock and unlock the screen I can verify that:
1. the extension throws an error: `TypeError: item is null` (I verified that in [Extension Manager](https://mattjakeman.com/apps/extension-manager))
2. the error is not thrown anymore once I disable the [GameMode](https://github.com/gicmo/gamemode-extension) extension.

Try checking if you can replicate this bug when only GameMode (or whatever other extension is causing it for you), AppIndicator and Hide Items are enabled.

**Comment by fablevi** [comment]
Hey, i think i fixed the first issue  while ago, i not close this issue if you still see some bugs:) Thanks for the report.

**Comment by fablevi** [comment]
For the secound comment, i dont think im need to be responsibe for others code. I dont know what Gamemode extension make in the background, and i dont have time to figure out how to fix it. I only take the St.Buttons on the rightPanel and hide and unhide them. Im sorry for saying this but i wont have time and money to fix this issue. If you have time or knowlage how to fix it, create a fork or pull request and i will implement it.

Thanks for your cooperation :)
