### ISSUE TITLE
Small inconsistencies in appearance

### ISSUE THREAD

**Issue by Naezr** [fablevi/HideItems#3]
The button is too long relative to the icon inside it. I suggest to make the button shorter. Also, the arrow icon is too thin and does not match the standard GNOME style. Maybe you could use a system-provided icon instead of your own to match different themes.

![изображение](https://github.com/fablevi/HideItems/assets/95460152/67d6020d-ff99-4352-9816-33161ede0e46)
![изображение](https://github.com/fablevi/HideItems/assets/95460152/5ed4443c-d30a-42b5-b9e0-fba087291f7a)

Overall though, it's a very cool extension, especially with the introduction of customization of which icons to hide. This is very handy because it allows you to hide not only tray icons, as in Tray Icons Reloaded, but also buttons of other extensions.

Also, as an idea for development I can suggest this:
You could make it so that when you click on a button, hidden icons would appear not in the panel, but in a popup window, like Windows Tray. It would be very cool, taking into account that buttons of any extensions could be placed there.

**Comment by hedgieinsocks** [comment]
Yeah, pls consider using these:

left-symbolic.svg

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" height="16px" viewBox="0 0 16 16" width="16px"><path d="m 9.292969 13.707031 l -5 -5 c -0.390625 -0.390625 -0.390625 -1.023437 0 -1.414062 l 5 -5 c 0.390625 -0.390625 1.023437 -0.390625 1.414062 0 s 0.390625 1.023437 0 1.414062 l -4.292969 4.292969 l 4.292969 4.292969 c 0.390625 0.390625 0.390625 1.023437 0 1.414062 s -1.023437 0.390625 -1.414062 0 z m 0 0" fill="white" fill-rule="evenodd"/></svg>
```

right-symbolic.svg
 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" height="16px" viewBox="0 0 16 16" width="16px"><path d="m 6.707031 13.707031 l 5 -5 c 0.390625 -0.390625 0.390625 -1.023437 0 -1.414062 l -5 -5 c -0.390625 -0.390625 -1.023437 -0.390625 -1.414062 0 s -0.390625 1.023437 0 1.414062 l 4.292969 4.292969 l -4.292969 4.292969 c -0.390625 0.390625 -0.390625 1.023437 0 1.414062 s 1.023437 0.390625 1.414062 0 z m 0 0" fill="white" fill-rule="evenodd"/></svg>
```

Also, it would be nice to set the max width of the button pill to 51 which seems to be the standard (like language switch). 

By the way, I have to use my https://github.com/hedgieinsocks/gnome-extension-lineup to normalize the indicators. Perhaps the dev would be interested in implementing something like that.

**Comment by fablevi** [comment]
Okey, i will test new icon styles to mix in GNOME's style, but the icon width is the default, i'm not change anything about it. Maybe if i have some time i will write some settings to set the icon width as you want, but rn i don't have any time. Thanks for the report :)
