### ISSUE TITLE
Suggestions : Get better other GNOME extensions detection compatibility

### ISSUE THREAD

**Issue by Anifyuli** [fablevi/HideItems#7]
Hello, Mister.
I want to share references for developing other GNOME Shell extension on top bar based on [this extension](https://gitlab.gnome.org/julianschacher/top-bar-organizer). I wish your extension can better other extension detection after read piece of codes from mentioned repositories. I like this extension.
Sorry my English. I glad waiting next updates from this cool extension. Thanks for read my issue

**Comment by fablevi** [comment]
Hey 😀

Its hard to work with other extensions. I dont have to much time now, and probably this will never happen. Sorry about it :C
