### ISSUE TITLE
Icon's menu popup position is wrong when the icon is hidden

### ISSUE THREAD

**Issue by HironTez** [fablevi/HideItems#8]
With visible icons:
![Screenshot from 2024-06-27 11-36-48](https://github.com/fablevi/HideItems/assets/81362525/7c189b9b-e7da-4494-86d6-f2dbf108db4d)

With hidden icons:
![Screenshot from 2024-06-27 11-37-04](https://github.com/fablevi/HideItems/assets/81362525/12490adf-cca9-4cfc-94f1-fce174dda675)

As you can see the popup is positioned not in the right place and even on the wrong monitor and therefore is not fully visible.

The extension is [Clipboard History](https://extensions.gnome.org/extension/4839/clipboard-history/) but the issue persists with all extensions.

**Comment by fablevi** [comment]
Hey, so this happens because the window isnt see the icon on the top bar. Its a gnome issue/feature idk. I dont think i can help it sorry :c
